export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';

export const REQUEST_POSTS = 'REQUEST_POSTS'
export const RECEIVE_POSTS = 'RECEIVE_POSTS'
export const RE_REQUEST_POSTS = 'RE_REQUEST_POSTS'
export const RE_RECEIVE_POSTS = 'RE_RECEIVE_POSTS'

export const REQUEST_DETAIL = 'REQUEST_DETAIL'
export const RECEIVE_DETAIL = 'RECEIVE_DETAIL'

export const REQUEST_COMMENTS = 'REQUEST_COMMENTS'
export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS'
export const RE_REQUEST_COMMENTS = 'RE_REQUEST_COMMENTS'
export const RE_RECEIVE_COMMENTS = 'RE_RECEIVE_COMMENTS'

export const SELECT_SUB_REDDIT = 'SELECT_SUB_REDDIT'
export const INVALIDATE_SUB_REDDIT = 'INVALIDATE_SUB_REDDIT'
export const REQUEST_SUB_REDDITS = 'REQUEST_SUB_REDDITS'
export const RECEIVE_SUB_REDDITS = 'RECEIVE_SUB_REDDITS'
export const RE_REQUEST_SUB_REDDITS = 'RE_REQUEST_SUB_REDDITS'
export const RE_RECEIVE_SUB_REDDITS = 'RE_RECEIVE_SUB_REDDITS'

export const SELECT_REDDIT = 'SELECT_REDDIT'
export const INVALIDATE_REDDIT = 'INVALIDATE_REDDIT'

export const SELECT_REDDIT_ID = 'SELECT_REDDIT_ID'




