export { default as Home } from './home/Home'
export { default as About } from './home/About'
export { Form, DefaultFrom, InitFrom, ValidateFrom } from './home/forms'
export { default as FirstPage } from './FirstPage'
export { default as DetailPage } from './DetailPage'
